# Funding sources — shows "Sponsor" button on the GitHub repo page.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [elmoorx0]
patreon: elmoorx
open_collective: elmoorx
ko_fi: elmoorx
custom: ["https://www.paypal.com/donate/?hosted_button_id=ELMOORX"]
