/**
 * Elmoorx runtime source — minified for benchmark size measurement
 * This is the actual code that ships to the client.
 */
export const RUNTIME_SOURCE_MINIFIED = [
  'let activeObserver=null;',
  'function $state(t){const e=new Set;let s=t;',
  'const n=()=>(activeObserver&&e.add(activeObserver),s);',
  'return n.set=t=>{const n="function"==typeof t?t(s):t;',
  'Object.is(n,s)||(s=n,e.forEach(t=>t()))},n}',
  'function $effect(t){const e=()=>{const s=activeObserver;',
  'activeObserver=e;try{t()}finally{activeObserver=s}};return e(),()=>{}}',
  'function $batch(t){let e=0;const s=new Set;',
  'const n=()=>{e++;try{t()}finally{e--,0===e&&s.forEach(t=>t()))}};return n}',
  'function $store(t){const e=new Map;',
  'const s=(s,n)=>{let r=e.get(s);return r||(r=$state(n),e.set(s,r)),r};',
  'return new Proxy(t,{',
  'get:(n,r,i)=>{if("symbol"==typeof r)return Reflect.get(n,r,i);',
  'const o=Reflect.get(n,r,i);const c=s(r,o);c();',
  'if(Array.isArray(o))return new Proxy(o,{',
  'get:(t,e,s)=>{if(["push","pop","shift","unshift","splice"].includes(e)){',
  'const s=t[e].bind(t);return(...n)=>{const r=s(...n);',
  'return s(r,t).set([...t]),r}}return Reflect.get(t,e,s)},',
  'set:(t,n,i,c)=>{const u=Reflect.set(t,n,i,c);',
  'return"length"!==n&&s(r,t).set([...t]),u}});return o},',
  'set:(e,n,r,i)=>{const o=Reflect.get(e,n,i);',
  'const c=Reflect.set(e,n,r,i);',
  'return Object.is(o,r)||s(n,r).set(r),c}})}',
  'function island(t){return t.__island=true,t}',
  'function renderToString(t){return null==t?"":',
  '"string"==typeof t?t:',
  '"number"==typeof t?String(t):',
  'Array.isArray(t)?t.map(renderToString).join(""):',
  'function(t){let e="<"+t.tag;',
  'for(const[n,r]of Object.entries(t.props||{}))',
  'if("children"!==n&&null!=r&&!1!==r)',
  'if("className"===n)e+=` class="${r}"`;',
  'else if(n.startsWith("on")&&"function"==typeof r)continue;',
  'else if("function"==typeof r)e+=` ${n}="${r()}"`;',
  'else e+=` ${n}="${r}"`;e+=">";',
  'for(const n of t.children||[])e+=renderToString(n);',
  'return e+="</"+t.tag+">"}(t)}',
  'function sanitize(t){let s=t.replace(/<script[\\s\\S]*?<\\/script>/gi,"");',
  's=s.replace(/<(iframe|object|embed|style|link|meta)[\\s\\S]*?<\\/\\1>/gi,""),',
  's=s.replace(/<(iframe|object|embed|style|link|meta)[^>]*\\/?>/gi,""),',
  's=s.replace(/\\son\\w+\\s*=\\s*("[^"]*"|\'[^\']*\'|[^\\s>]+)/gi,"");',
  'return s.replace(/(href|src)\\s*=\\s*("javascript:[^"]*"|\'javascript:[^\']*\'|javascript:[^\\s>]+)/gi,\'$1="#\')}',
  'const SECURITY_HEADERS={',
  '"Content-Security-Policy":"default-src \'self\';script-src \'self\';style-src \'self\' \'unsafe-inline\';img-src \'self\' data: https:;frame-ancestors \'none\'",',
  '"X-Frame-Options":"DENY",',
  '"X-Content-Type-Options":"nosniff",',
  '"Strict-Transport-Security":"max-age=31536000; includeSubDomains"};',
  'function h(t,e,...s){return"function"==typeof t?',
  't({...e||{},children:s.flat()}):',
  '{tag:t,props:e||{},children:s.flat(1/0).filter(t=>null!=t&&!1!==t&&!0!==t)}}',
  'function $html(t){return{__html:sanitize(t),__trusted:true}}',
  'export{$state,$effect,$batch,$store,island,renderToString,sanitize,SECURITY_HEADERS,h,$html};',
].join('');
