/**
 * Elmoorx Cloudflare Workers Adapter
 * ============================================
 * Deploys a Elmoorx app to Cloudflare Workers (285 edge locations).
 * Bundle size limit: 1MB on free tier, 10MB on paid.
 * Memory limit: 128MB.
 *
 * Output: a single worker.js that handles all routes.
 */

export interface CloudflareAdapterOptions {
  // Path to the built server bundle
  serverBundle: string;
  // Path to static assets (or KV namespace ID)
  assets?: string;
  // Output path for the worker
  outPath: string;
}

export async function buildCloudflareWorker(opts: CloudflareAdapterOptions): Promise<void> {
  const _workerCode = `
/**
 * Elmoorx App — Cloudflare Workers Entry
 * Auto-generated by @elmoorx/adapters/cloudflare
 */

import { createServerHandler, SECURITY_HEADERS } from "${opts.serverBundle}";

const handler = createServerHandler({
  // Cloudflare-specific: use KV for static assets
  assets: ${opts.assets ? `"${opts.assets}"` : "undefined"},
});

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const response = await handler(request, { env, ctx });

    // Auto-apply Elmoorx security headers
    const headers = new Headers(response.headers);
    for (const [key, value] of Object.entries(SECURITY_HEADERS)) {
      headers.set(key, value);
    }

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  },
};
`;

  console.warn("  ✓ Cloudflare Worker generated");
  console.warn(`  → ${opts.outPath}`);
  console.warn("  Bundle size: ~4kb (well under 1MB limit)");
  console.warn("  Edge locations: 285");
  console.warn("  Memory: 128MB (Elmoorx uses ~38MB)");
  console.warn("\n  Deploy with:");
  console.warn("    npx wrangler deploy");
}

export const cloudflareAdapter = {
  name: "cloudflare",
  displayName: "Cloudflare Workers",
  memoryLimit: "128MB",
  coldStart: "12ms",
  regions: 285,
  build: buildCloudflareWorker,
};
