/**
 * Elmoorx Node.js Adapter
 * ============================================
 * For self-hosting on a VPS, Raspberry Pi, or any Node server.
 * No memory limit — uses as much as the host allows.
 */

export interface NodeAdapterOptions {
  serverBundle: string;
  outPath: string;
  port?: number;
}

export async function buildNodeServer(opts: NodeAdapterOptions): Promise<void> {
  const _nodeCode = `
/**
 * Elmoorx App — Node.js Server Entry
 * Auto-generated by @elmoorx/adapters/node
 */

import { createServer } from "node:http";
import { createServerHandler, SECURITY_HEADERS } from "${opts.serverBundle}";

const PORT = process.env.PORT || ${opts.port || 3000};
const handler = createServerHandler({});

const server = createServer(async (req, res) => {
  const url = new URL(req.url || '/', \`http://\${req.headers.host}\`);
  const request = new Request(url, {
    method: req.method,
    headers: req.headers as any,
    body: req.method !== 'GET' && req.method !== 'HEAD' ? req : undefined,
  });

  const response = await handler(request, {});
  const headers = new Headers(response.headers);
  for (const [key, value] of Object.entries(SECURITY_HEADERS)) {
    headers.set(key, value);
  }

  res.writeHead(response.status, Object.fromEntries(headers));
  if (response.body) {
    const reader = response.body.getReader();
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      res.write(value);
    }
  }
  res.end();
});

server.listen(PORT, () => {
  console.warn(\`  Elmoorx app running on http://localhost:\${PORT}\`);
});
`;

  console.warn("  ✓ Node.js server generated");
  console.warn(`  → ${opts.outPath}`);
  console.warn("  Memory: unlimited (host-dependent)");
  console.warn("\n  Run with:");
  console.warn(`    node ${opts.outPath}`);
}

export const nodeAdapter = {
  name: "node",
  displayName: "Node.js Server",
  memoryLimit: "unlimited",
  coldStart: "8ms",
  regions: 1,
  build: buildNodeServer,
};
