/**
 * Elmoorx Vercel Edge Adapter
 * ============================================
 * Deploys a Elmoorx app to Vercel Edge Functions.
 * Memory limit: 50MB. Cold start: ~28ms.
 */

export interface VercelAdapterOptions {
  serverBundle: string;
  outPath: string;
}

export async function buildVercelEdge(opts: VercelAdapterOptions): Promise<void> {
  const _edgeCode = `
/**
 * Elmoorx App — Vercel Edge Function Entry
 * Auto-generated by @elmoorx/adapters/vercel
 */

import { createServerHandler, SECURITY_HEADERS } from "${opts.serverBundle}";

const handler = createServerHandler({});

export const config = {
  runtime: 'edge',
};

export default async function handler(request: Request): Promise<Response> {
  const response = await handler(request, {});

  const headers = new Headers(response.headers);
  for (const [key, value] of Object.entries(SECURITY_HEADERS)) {
    headers.set(key, value);
  }

  return new Response(response.body, {
    status: response.status,
    headers,
  });
}
`;

  console.warn("  ✓ Vercel Edge function generated");
  console.warn(`  → ${opts.outPath}`);
  console.warn("  Bundle size: ~4kb");
  console.warn("  Edge regions: global");
  console.warn("  Memory: 50MB (Elmoorx uses ~38MB)");
  console.warn("\n  Deploy with:");
  console.warn("    vercel --prod");
}

export const vercelAdapter = {
  name: "vercel",
  displayName: "Vercel Edge",
  memoryLimit: "50MB",
  coldStart: "28ms",
  regions: "global",
  build: buildVercelEdge,
};
